### PR TITLE
Initial Changes -- No Test yet

### PR DESCRIPTION
**Pull request by ofonimefrancis**
Please do not merge, just take a look at the way i structured the app and give me feedback on your thoughts. The handlers i suppose we can create a custom handler that does alot of the functionalities we need the API to do, cos i have a feeling this codebase will break.

### CODE REVIEW

**Comment by gaurav-gogia** [comment]
Well it does looks a lot more organized than my version, could you give me a summary or something or the idea that you used  for this? So that I can follow the same practice for this project and for future references  ^.^

**Comment by ofonimefrancis** [comment]
The idea is to have a config pointer in your model functions, ideally the database object will be contained in the config, so we have access to our mongo DB always and when we about to use it we use the Copy() method. Also i think we need to take time and work on the handlers and explore stuffs like logging and middleware library like alice to chain them. 

- The current implementation will fail because there is no distinct separation between the controllers and the models(Thats what i will work on when i have time to touch the code base)

**Comment by gaurav-gogia** [comment]
Agreed, also I read somewhere that in order to utilize mongodb's session efficiently I should create only one session and then use the same in whole application. I haven't been able to implement that because well I didn't really understand how to. I will read up more on that again to see what can be done and what are the best practices :)

**Comment by ofonimefrancis** [comment]
The pattern you used initially was the Global variable pattern i guess, you had a *mgo.Session in a global config but i thought the use was a bit disjointed. There are a lot of patterns am currently researching on like the Context pattern and Dependency Injection pattern. Global variable pattern is good for some reasons mainly when u have an application that is single packaged, but what happens when u cannot keep track of the variable or mistakenly leak memory. That is where other patterns come to play

**Comment by gaurav-gogia** [comment]
I see, where can I learn about these patterns? Do I just google search there names or are there any dedicated books or courses available for them?

**Comment by ofonimefrancis** [comment]
http://www.alexedwards.net/blog/organising-database-access

**Comment by gaurav-gogia** [comment]
Thanks

**Comment by ofonimefrancis** [comment]
As per the structural organization, i made some small changes to the previous pull request. Handlers and models are segregated from the main package, so we can find files based on the functions they perform.

I used gorilla mux to gives us more control of the server, and since gorilla mux plays nicely with the Handler interface i decided to go that route.

We might need to use context more in the years to come, but for now i decided to pass the config as the first argument to our handler functions

**Comment by ofonimefrancis** [comment]
You can go along and merge, i've tried it locally and via Postman to test the api

**Pull request merged**
